version: "3.7"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile

    volumes:
      - .:/django


    ports:
      - 8000:8000
    image: python-image1:latest
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000