# Generated by Django 4.1 on 2022-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_user_user_type_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'admin'), ('shopuser', 'shopuser'), ('customer', 'customer')], max_length=20),
        ),
    ]
