# Generated by Django 4.1 on 2022-08-25 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_alter_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=40)),
                ('product_name', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('product_size', models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L'), ('xl', 'XL'), ('xxl', 'XXL')], max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
