# Generated by Django 4.1 on 2022-08-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0011_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, default='images/background.jpeg', null=True, upload_to=''),
        ),
    ]
