# Generated by Django 4.1 on 2022-09-01 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0019_remove_myorders_wishlist_myorders_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorders',
            name='product',
        ),
        migrations.AddField(
            model_name='myorders',
            name='cartitems',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.cartitems'),
        ),
    ]
