# Generated by Django 4.1 on 2022-09-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0020_remove_myorders_product_myorders_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myorders',
            name='cartitems',
        ),
        migrations.AddField(
            model_name='myorders',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10),
        ),
        migrations.AddField(
            model_name='myorders',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='product_img',
            field=models.ImageField(blank=True, default='images/background.jpeg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='myorders',
            name='product_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='product_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='product_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
