# Generated by Django 4.1 on 2022-09-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0021_remove_myorders_cartitems_myorders_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
