# Generated by Django 4.1 on 2022-09-02 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0023_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variations',
            old_name='geeks_field',
            new_name='color',
        ),
        migrations.AlterField(
            model_name='variations',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='ecomapp.product'),
        ),
    ]
