# Generated by Django 4.1 on 2022-09-05 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0024_rename_geeks_field_variations_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myorders',
            old_name='product_size',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='mob',
            new_name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_size',
        ),
        migrations.RemoveField(
            model_name='variations',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cartitems',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='color',
            field=models.CharField(blank=True, choices=[('Red', 'red'), ('Black', 'Black'), ('Blue', 'Blue'), ('White', 'White'), ('Gray', 'Gray')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='product_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='myorders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myorders',
            name='wishlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecomapp.wishlist'),
        ),
        migrations.AddField(
            model_name='user',
            name='addressof_customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variations',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='myorders',
            name='quantity',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
